version: 1
project:
  # Point two levels up to the monorepo root
  targetProjectRoot: ../../

sanitation:
  maxUploadSizeMb: 500
  acceptedExtensions:
    - ts
    - tsx
    - js
    - jsx
    - json
    - yaml
    - md
    - html
    - css
  denyPatterns:
    - .git
    - node_modules
    - dist
    - .idx
    - .pnpm-store
    # Ignore the output cache so we don't scan our own dumps
    - packages/desktop/public/source-dump