name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - dev # Or main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- PNPM SETUP ---
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      # ------------------

      - run: pnpm install --frozen-lockfile
      - run: pnpm build:web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTEXTSLICER }}'
          channelId: live
          projectId: contextslicer